name: jain_songs
description: Contains Jain Bhajans

publish_to: 'none'
version: 1.3.3+13

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  connectivity: ^3.0.3
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_analytics: ^8.1.2
  url_launcher: ^6.0.3
  flutter_share: ^2.0.0
  shared_preferences: ^2.0.5
  firebase_crashlytics: ^2.0.6
  firebase_database: ^7.1.1
  device_info: ^2.0.0
  firebase_performance: ^0.7.0+5
  flutter_windowmanager: ^0.1.0
  webview_flutter: ^2.0.4
  firebase_auth: ^1.4.1
  package_info: ^2.0.0
  firebase_messaging: ^10.0.2
  firebase_dynamic_links: ^2.0.6
  flutter_local_notifications: ^5.0.0+4
  random_string: ^2.1.0
  fluttertoast: ^8.0.6
  animated_bottom_navigation_bar: ^0.3.2
  firebase_remote_config: ^0.10.0+2 
  sortedmap: ^0.5.0
  speech_to_text: ^4.2.1
  google_fonts: ^2.1.0
  onesignal_flutter: ^3.0.0
  flutter_keyboard_visibility: ^5.0.3
  flutter_inappwebview: ^5.3.2
  google_mobile_ads: ^0.13.2+1
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/Logo-adaptive.png"

flutter:
  assets:
    - images/

  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
