name: jain_songs
description: Contains Jain Bhajans

publish_to: "none"
version: 2.1.0+19

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.2.0
  better_player: ^0.0.82
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.7.1
  connectivity_plus: ^4.0.1
  device_info_plus: ^8.2.2
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.13.0
  flutter_share: ^2.0.0
  firebase_analytics: ^10.4.1
  firebase_crashlytics: ^3.3.1
  firebase_database: ^10.2.1
  firebase_performance: ^0.9.2+1
  firebase_remote_config: ^4.2.1
  firebase_auth: ^4.6.1
  firebase_messaging: ^14.6.1
  firebase_dynamic_links: ^5.3.1
  firebase_storage: ^11.2.1
  flutter_share_me: ^1.3.0
  flutter_windowmanager: ^0.2.0
  fluttertoast: ^8.0.6
  flutter_keyboard_visibility: ^5.0.3
  flutter_inappwebview: ^5.3.2
  google_fonts: ^4.0.4
  google_mobile_ads: ^3.0.0
  image_picker: ^1.0.4
  package_info_plus: ^3.1.2
  path: any
  path_provider: ^2.0.3
  permission_handler: ^11.0.0
  provider: ^6.0.0
  random_string: ^2.1.0
  shared_preferences: ^2.0.5
  sortedmap: ^0.5.0
  speech_to_text: ^6.1.1
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.3
  webview_flutter: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/Logo-adaptive.png"

flutter:
  assets:
    - images/
    - assets/songs_database.db

  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
