name: jain_songs
description: Contains Jain Bhajans

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  connectivity: ^0.4.9+3
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  modal_progress_hud: ^0.1.3
  firebase_analytics: ^6.0.2
  url_launcher: ^5.7.2
  flutter_share: ^1.0.2+1
  shared_preferences: ^0.5.12+2
  progress_hud: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
