name: jain_songs
description: Contains Jain Bhajans

publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  connectivity: ^0.4.9+3
  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.1+3
  modal_progress_hud: ^0.1.3
  firebase_analytics: ^6.0.2
  url_launcher: ^5.7.2
  flutter_share: ^1.0.2+1
  shared_preferences: ^0.5.12+2
  progress_hud: ^1.1.0
  firebase_crashlytics: ^0.2.3
  firebase_database: "^4.3.0"
  device_info: ^1.0.0
  firebase_performance: ^0.4.2
  firebase_admob: ^0.10.3
  flutter_windowmanager: ^0.0.2
  translator: ^0.1.5
  webview_flutter: ^1.0.7
  firebase_auth: "^0.18.4+1"
  package_info: ^0.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/Logo-adaptive.png"

flutter:
  assets:
    - images/

  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
