name: jain_songs
description: Contains Jain Bhajans

publish_to: 'none'
version: 1.4.0+15

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  connectivity: ^3.0.3
  firebase_core: ^1.3.0
  cloud_firestore: ^3.1.8
  firebase_analytics: ^9.1.0
  url_launcher: ^6.0.3
  flutter_share: ^2.0.0
  shared_preferences: ^2.0.5
  firebase_crashlytics: ^2.0.6
  firebase_database: ^9.0.6
  device_info: ^2.0.0
  firebase_performance: ^0.8.0+5
  flutter_windowmanager: ^0.2.0
  webview_flutter: ^3.0.0
  firebase_auth: ^3.3.7
  package_info: ^2.0.0
  firebase_messaging: ^11.2.6
  firebase_dynamic_links: ^4.0.6
  flutter_local_notifications: ^9.3.2
  random_string: ^2.1.0
  fluttertoast: ^8.0.6
  animated_bottom_navigation_bar: ^0.3.2
  firebase_remote_config: ^2.0.0 
  sortedmap: ^0.5.0
  speech_to_text: ^5.4.3
  google_fonts: 2.1.0
  onesignal_flutter: ^3.2.3
  flutter_keyboard_visibility: ^5.0.3
  flutter_inappwebview: ^5.3.2
  google_mobile_ads: ^1.1.0
  provider: ^6.0.0
  image_picker: ^0.8.4
  path_provider: ^2.0.3
  firebase_storage: ^10.0.3
  sqflite: ^2.0.0+4
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/Logo-adaptive.png"

flutter:
  assets:
    - images/
    - assets/songs_database.db

  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
