name: jain_songs
description: Contains Jain Bhajans

publish_to: 'none'
version: 1.2.1+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  connectivity: ^3.0.3
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  modal_progress_hud: ^0.1.3
  firebase_analytics: ^7.0.1
  url_launcher: ^6.0.3
  flutter_share: ^2.0.0
  shared_preferences: ^2.0.5
  progress_hud: ^1.1.0
  firebase_crashlytics: ^0.4.0+1
  firebase_database: "^6.0.0"
  device_info: ^2.0.0
  firebase_performance: ^0.5.0+1
  firebase_admob: ^0.11.0+2
  flutter_windowmanager: ^0.0.2
  webview_flutter: ^2.0.4
  firebase_auth: "^0.20.1"
  package_info: ^2.0.0
  firebase_messaging: ^8.0.0-dev.15
  youtube_player_flutter: ^8.0.0
  mopub_flutter: ^1.2.2+1
  firebase_dynamic_links: ^0.7.0
  flutter_local_notifications: ^4.0.1+2
  random_string: ^2.1.0
  fluttertoast: ^8.0.6
  animated_bottom_navigation_bar: ^0.3.2
  firebase_remote_config: ^0.6.0
  sortedmap: ^0.4.2+1
  keyboard_visibility: ^0.5.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/Logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/Logo-adaptive.png"

flutter:
  assets:
    - images/

  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
