// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAif0AdUdYZ0IH06xcdaoNcwAepdIPLK2Y',
    appId: '1:456042169963:android:ae3fc31522dd1a8547932e',
    messagingSenderId: '456042169963',
    projectId: 'jain-songs-29c85',
    databaseURL: 'https://jain-songs-29c85.firebaseio.com',
    storageBucket: 'jain-songs-29c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs9Z0dq9IeoqlZN1z-s3YTPiHo9oT0rI0',
    appId: '1:456042169963:ios:ba7c24b030a1780447932e',
    messagingSenderId: '456042169963',
    projectId: 'jain-songs-29c85',
    databaseURL: 'https://jain-songs-29c85.firebaseio.com',
    storageBucket: 'jain-songs-29c85.appspot.com',
    androidClientId: '456042169963-aeb161lttc08fau688sabrsd78qbqfml.apps.googleusercontent.com',
    iosBundleId: 'com.JainDevelopers.jainSongs',
  );
}
